outputFileName: outputXML
withns: true
sfdc_metadata: http://soap.sforce.com/2006/04/metadata

#Parser profile note
parserProfileNote: 1
inputSysProfilePath: C:/temp/profiles/Admin.profile-meta.xml
note:
  applicationVisibilities: [application]
  classAccesses: [apexClass]
  fieldPermissions: [field]
  layoutAssignments: [layout]
  objectPermissions: [object]
  pageAccesses: [apexPage]
  recordTypeVisibilities: [recordType]
  tabVisibilities: [tab]
  userPermissions: [name]

# Parser profile data
outputFileToCsvByList: 0
OutputFileToCsvByMatrix: 0
OutputFileToExlByMatrix: 0

inputdir: C:/temp/profiles

# For All(List, Matrix)
csv:
  targetNote: userPermissions
  targetSubNotes: [filename, name, enabled]
  # For Matrix
  targetKey: name

# For Excel(Matrix)
exl:
  userPermissions:
    targetNote: userPermissions
    load: true
    targetSubNotes: [filename, name, enabled]
    targetKey: name
    targetObjs: [CustomMobileAppsAccess,ViewHelpLink]
  tabVisibilities:
    targetNote: tabVisibilities
    load: true
    targetSubNotes: [filename, tab, visibility]
    targetKey: tab
    targetObjs: [standard-Contact,standard-Task]

# For Excel
# targetNote:
#   userPermissions:
#     targetKey: name
#     targetSubNotes: [filename, name, enabled]
#     targetObjs: [CustomMobileAppsAccess,ViewHelpLink]
#   tabVisibilities:
#     targetKey: tab
#     targetSubNotes: [filename, tab, visibility]
#     targetObjs: [standard-Task,standard-Contact]

#targetNote: objectPermissions
#targetKey: object
#targetSubNotes: [filename, object, allowRead]
#targetObjs: [Account, ActivityStatus__c]

#inputdir: C:/temp/profiles
#withns: false
#targetNote: fieldPermissions
#targetSubNotes: [filename, field, readable, editable]

#inputdir: C:/temp/queues
#withns: true
#targetNote: queueSobject
#targetSubNotes: [filename, sobjectType]