outputFileName: outputXML
sfdc_metadata: http://soap.sforce.com/2006/04/metadata

outputFileToCsvByList: 0
OutputFileToCsvByMatrix: 0
OutputFileToExlByMatrix: 1

inputdir: C:/temp/profiles
withns: true

# For All(List, Matrix)
common:
  targetNote: userPermissions
  targetSubNotes: [filename, name, enabled]
  # For CSV(Matrix)
  csv:
    targetKey: name
  # For Excel(Matrix)
  exl:
    targetKey: name
    targetObjs: [CustomMobileAppsAccess,ViewHelpLink]

# For Excel
# targetNote:
#   userPermissions:
#     targetKey: name
#     targetSubNotes: [filename, name, enabled]
#     targetObjs: [CustomMobileAppsAccess,ViewHelpLink]
#   tabVisibilities:
#     targetKey: tab
#     targetSubNotes: [filename, tab, visibility]
#     targetObjs: [standard-Task,standard-Contact]

#targetNote: objectPermissions
#targetKey: object
#targetSubNotes: [filename, object, allowRead]
#targetObjs: [Account, ActivityStatus__c]

#inputdir: C:/temp/profiles
#withns: false
#targetNote: fieldPermissions
#targetSubNotes: [filename, field, readable, editable]

#inputdir: C:/temp/queues
#withns: true
#targetNote: queueSobject
#targetSubNotes: [filename, sobjectType]